<a href="https://colab.research.google.com/github/Sylwiaes/numpy_pandas_cwiczenia/blob/main/01_numpy_cwiczenia/051_060_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 51](#1)
* [Ćwiczenie 52](#2)
* [Ćwiczenie 53](#3)
* [Ćwiczenie 54](#4)
* [Ćwiczenie 55](#5)
* [Ćwiczenie 56](#6)
* [Ćwiczenie 57](#7)
* [Ćwiczenie 58](#8)
* [Ćwiczenie 59](#9)
* [Ćwiczenie 60](#10)

### <a name='0'></a>Import biblioteki

In [ ]:
import numpy as np

np.random.seed(42)
np.__version__

'1.19.5'

### <a name='1'></a> Ćwiczenie 51
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [ ]:
# tutaj wpisz rozwiązanie
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

np.concatenate((A, B))

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [ ]:
# tutaj wpisz rozwiązanie
np.concatenate((A, B), axis=1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Ćwiczenie 52
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Połącz te tablice w jedną tak jak pokazano poniżej:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [ ]:
# tutaj wpisz rozwiązanie
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

np.concatenate((data, target), axis=1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Ćwiczenie 53
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [ ]:
# tutaj wpisz rozwiązanie
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

np.column_stack((feature1, feature2, feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Ćwiczenie 54
Podana jest poniższa dwuwymiarowa tablica:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Podziel tablicę na 3 części tak aby pierwsze dwie kolumny stanowiły pierwszą tablicę $A1$, cztery kolejne drugą tablicę $A2$ oraz dwie ostatnie trzecią tablicę $A3$.

__Wskazówka:__ Wykorzystaj funkcję _np.split()_.

In [ ]:
# tutaj wpisz rozwiązanie
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A

array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])

In [ ]:
A1, A2, A3 = np.split(A, [2, 6], axis=1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Ćwiczenie 55
Podana jest poniższa tablica $A$:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Wyznacz łączną liczbę elementów niezerowych dla tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.


In [ ]:
# tutaj wpisz rozwiązanie
A = np.random.randint(low=0, high=2, size=(10, 6))
np.count_nonzero(A)

31

Wyznacz łączną liczbę elementów niezerowych dla każdego wiersza tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.

In [ ]:
# tutaj wpisz rozwiązanie
np.count_nonzero(A, axis=1)

array([2, 1, 3, 4, 6, 3, 1, 5, 4, 2])

### <a name='6'></a> Ćwiczenie 56
Poniżej podana jest przykładowa tablica $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować tablice z określoną precyzją. Ustaw jej wartość na 4 i wydrukuj tablicę $A$.



In [ ]:
# tutaj wpisz rozwiązanie
A = np.random.randn(10, 4)
A

array([[-0.07201012,  1.0035329 ,  0.36163603, -0.64511975],
       [ 0.36139561,  1.53803657, -0.03582604,  1.56464366],
       [-2.6197451 ,  0.8219025 ,  0.08704707, -0.29900735],
       [ 0.09176078, -1.98756891, -0.21967189,  0.35711257],
       [ 1.47789404, -0.51827022, -0.8084936 , -0.50175704],
       [ 0.91540212,  0.32875111, -0.5297602 ,  0.51326743],
       [ 0.09707755,  0.96864499, -0.70205309, -0.32766215],
       [-0.39210815, -1.46351495,  0.29612028,  0.26105527],
       [ 0.00511346, -0.23458713, -1.41537074, -0.42064532],
       [-0.34271452, -0.80227727, -0.16128571,  0.40405086]])

In [ ]:
np.set_printoptions(precision=4)
A

array([[-0.072 ,  1.0035,  0.3616, -0.6451],
       [ 0.3614,  1.538 , -0.0358,  1.5646],
       [-2.6197,  0.8219,  0.087 , -0.299 ],
       [ 0.0918, -1.9876, -0.2197,  0.3571],
       [ 1.4779, -0.5183, -0.8085, -0.5018],
       [ 0.9154,  0.3288, -0.5298,  0.5133],
       [ 0.0971,  0.9686, -0.7021, -0.3277],
       [-0.3921, -1.4635,  0.2961,  0.2611],
       [ 0.0051, -0.2346, -1.4154, -0.4206],
       [-0.3427, -0.8023, -0.1613,  0.4041]])

### <a name='7'></a> Ćwiczenie 57
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```





In [ ]:
# tutaj wpisz rozwiązanie
A = np.array([1.2e-6, 1.7e-7])
A

array([1.2e-06, 1.7e-07])

In [ ]:
np.set_printoptions(precision=8, suppress=True) #parametr suppress-tłumienie notacji wykładniczej
A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Ćwiczenie 58
Podana jest poniższa tablica numpy $A$:

```
A = np.random.randn(8, 4)
```
Usuń trzecią kolumnę z tablicy $A$.

__Oczekiwany wynik:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.delete()_.




In [ ]:
# tutaj wpisz rozwiązanie
A = np.random.randn(8, 4)
A

array([[ 1.8861859 ,  0.17457781,  0.25755039, -0.07444592],
       [-1.91877122, -0.02651388,  0.06023021,  2.46324211],
       [-0.19236096,  0.30154734, -0.03471177, -1.16867804],
       [ 1.14282281,  0.75193303,  0.79103195, -0.90938745],
       [ 1.40279431, -1.40185106,  0.58685709,  2.19045563],
       [-0.99053633, -0.56629773,  0.09965137, -0.50347565],
       [-1.55066343,  0.06856297, -1.06230371,  0.47359243],
       [-0.91942423,  1.54993441, -0.78325329, -0.32206152]])

In [ ]:
np.delete(A, [2], axis=1)

array([[ 1.8861859 ,  0.17457781, -0.07444592],
       [-1.91877122, -0.02651388,  2.46324211],
       [-0.19236096,  0.30154734, -1.16867804],
       [ 1.14282281,  0.75193303, -0.90938745],
       [ 1.40279431, -1.40185106,  2.19045563],
       [-0.99053633, -0.56629773, -0.50347565],
       [-1.55066343,  0.06856297,  0.47359243],
       [-0.91942423,  1.54993441, -0.32206152]])

### <a name='9'></a> Ćwiczenie 59
Podana jest tablica jednowymiarowa $v$ (wektor):

```
v = np.array([3, 4, -2])
```
Policz normę wektora $v$.


In [ ]:
# tutaj wpisz rozwiązanie
v = np.array([3, 4, -2])
v

array([ 3,  4, -2])

In [ ]:
np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Ćwiczenie 60
Poniżej podana jest przykładowa tablica $A$:


```
A = np.random.randint(10, size=(100, 30))
```
Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować 10 skrajnych elementów. Wydrukuj tablicę $A$.


In [ ]:
# tutaj wpisz rozwiązanie
A = np.random.randint(10, size=(100, 30))
A

array([[2, 1, 2, ..., 0, 8, 4],
       [4, 2, 4, ..., 6, 1, 1],
       [7, 1, 8, ..., 1, 2, 2],
       ...,
       [7, 9, 4, ..., 3, 9, 8],
       [9, 9, 0, ..., 5, 0, 0],
       [8, 9, 5, ..., 9, 4, 3]])

In [ ]:
np.set_printoptions(edgeitems=10)
A

array([[2, 1, 2, 5, 1, 7, 0, 6, 1, 9, ..., 7, 6, 5, 6, 4, 6, 0, 0, 8, 4],
       [4, 2, 4, 2, 8, 8, 5, 0, 6, 6, ..., 4, 7, 5, 3, 6, 7, 1, 6, 1, 1],
       [7, 1, 8, 0, 8, 0, 9, 9, 1, 5, ..., 8, 0, 2, 8, 1, 3, 3, 1, 2, 2],
       [0, 5, 7, 2, 4, 0, 9, 6, 9, 0, ..., 0, 3, 8, 8, 4, 3, 2, 2, 4, 9],
       [0, 4, 5, 6, 8, 2, 1, 2, 8, 6, ..., 5, 0, 3, 6, 1, 8, 7, 7, 6, 3],
       [1, 2, 5, 4, 7, 5, 5, 0, 3, 4, ..., 5, 7, 1, 5, 0, 3, 9, 2, 8, 2],
       [5, 0, 5, 3, 7, 8, 3, 9, 9, 5, ..., 1, 4, 5, 6, 4, 8, 0, 6, 9, 6],
       [3, 8, 4, 3, 6, 3, 2, 8, 7, 0, ..., 1, 6, 9, 3, 9, 7, 8, 6, 4, 7],
       [3, 1, 5, 8, 0, 9, 6, 9, 8, 9, ..., 5, 7, 5, 8, 8, 1, 9, 0, 1, 4],
       [3, 3, 8, 7, 5, 0, 1, 5, 1, 9, ..., 0, 0, 1, 5, 8, 3, 2, 7, 9, 8],
       ...,
       [7, 7, 0, 7, 1, 5, 0, 4, 6, 9, ..., 6, 7, 1, 9, 6, 7, 5, 5, 9, 0],
       [3, 0, 3, 1, 4, 9, 8, 9, 2, 7, ..., 7, 6, 2, 5, 8, 6, 2, 5, 3, 2],
       [8, 9, 1, 0, 1, 6, 9, 0, 5, 6, ..., 1, 0, 3, 4, 5, 4, 0, 2, 0, 4],
       [4, 5, 7, 9, 0, 3, 